import api from './api';

export const getMySubscription = () => api.get('/billing/subscription');
export const getMyInvoices = (params = {}) => api.get('/billing/invoices', { params });
export const getInvoiceById = (id) => api.get(`/billing/invoices/${id}`);
export const getInvoicePdf = (id) => api.get(`/billing/invoices/${id}/pdf`, { responseType: 'blob' });
export const getInvoiceUpiPayload = (id) => api.get(`/billing/invoices/${id}/upi-payload`);
export const exportInvoicesCsv = () => api.get('/billing/invoices/export/csv', { responseType: 'blob' });
export const getBillingDashboardStats = () => api.get('/billing/dashboard-stats');
export const getExpensesByCase = () => api.get('/billing/expenses-by-case');
export const createAdvocateInvoice = (data) => api.post('/billing/invoices', data);
export const updateAdvocateInvoice = (id, data) => api.put(`/billing/invoices/${id}`, data);
export const sendInvoiceReminderWhatsApp = (invoiceId) => api.post(`/billing/invoices/${invoiceId}/send-reminder`);
export const sendInvoiceReminder = (invoiceId, channel = 'whatsapp') => api.post(`/billing/invoices/${invoiceId}/reminder`, { channel });
export const recordPayment = (invoiceId, data) => api.post(`/billing/invoices/${invoiceId}/payments`, data);
export const getGstSummary = (params = {}) => api.get('/billing/gst-summary', { params });
export const listExpenses = (params = {}) => api.get('/billing/expenses', { params });
export const getExpensesMonthlyReport = (params = {}) => api.get('/billing/expenses/monthly-report', { params });
export const createExpense = (data) => api.post('/billing/expenses', data);
export const updateExpense = (id, data) => api.put(`/billing/expenses/${id}`, data);
export const deleteExpense = (id) => api.delete(`/billing/expenses/${id}`);
export const listTdsRecords = (params = {}) => api.get('/billing/tds', { params });
export const getTdsYearlyStatement = (params = {}) => api.get('/billing/tds/yearly-statement', { params });
export const createTdsRecord = (data) => api.post('/billing/tds', data);
export const getPackages = () => api.get('/billing/packages');
export const getPaymentGatewayStatus = () => api.get('/billing/payment-gateway-status');
export const createOrder = (data) => api.post('/billing/create-order', data);
export const verifyPayment = (data) => api.post('/billing/verify-payment', data);
